import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
# config :markdoc, MarkdocWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Allow connections from the Vite dev server and other localhost ports
config :markdoc, MarkdocWeb.Endpoint,
  check_origin: [
    "//localhost:4000",
    "//localhost:5173",
    "//localhost:3000",
    "//localhost:8080"
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
